export type Commitment = "egy-verseny" | "szezon"
export type Role = "matroz" | "trimmer" | "kormanyos" | "egyeb"
export type Level = "kezdo" | "halado" | "profi"

export type Listing = {
  id: string
  boatName: string
  image: string
  commitment: Commitment
  event: string
  location: string
  date: string
  role: Role
  level: Level
}

export const listings: Listing[] = [
  {
    id: "1",
    boatName: "Sirocco",
    image: "/boats/sirocco.png",
    commitment: "egy-verseny",
    event: "Kékszalag Erste Kör",
    location: "Balatonfüred",
    date: "2026. július 17–18.",
    role: "trimmer",
    level: "halado",
  },
  {
    id: "2",
    boatName: "Nemere II",
    image: "/boats/nemere.png",
    commitment: "szezon",
    event: "Balatoni Bajnokság – teljes szezon",
    location: "Balatonkenese",
    date: "2026. május – szeptember",
    role: "matroz",
    level: "kezdo",
  },
  {
    id: "3",
    boatName: "Avalon",
    image: "/boats/avalon.png",
    commitment: "egy-verseny",
    event: "Kékszalag nagytávú verseny",
    location: "Balatonfüred",
    date: "2026. július 24.",
    role: "kormanyos",
    level: "profi",
  },
  {
    id: "4",
    boatName: "Blue Horizon",
    image: "/boats/nemere.png",
    commitment: "egy-verseny",
    event: "Kékszalag – 2. forduló",
    location: "Tihany",
    date: "2026. augusztus 1–2.",
    role: "matroz",
    level: "halado",
  },
  {
    id: "5",
    boatName: "Asteria",
    image: "/boats/sirocco.png",
    commitment: "szezon",
    event: "Balaton nyári szezon",
    location: "Siófok",
    date: "2026. május – október",
    role: "trimmer",
    level: "profi",
  },
  {
    id: "6",
    boatName: "Mistral",
    image: "/boats/avalon.png",
    commitment: "egy-verseny",
    event: "Duna hajóverseny",
    location: "Budapest",
    date: "2026. szeptember 5.",
    role: "kormanyos",
    level: "halado",
  },
  {
    id: "7",
    boatName: "Viking Sky",
    image: "/boats/nemere.png",
    commitment: "szezon",
    event: "Csapatépítő és regatta szezon",
    location: "Zamárdi",
    date: "2026. április – szeptember",
    role: "matroz",
    level: "kezdo",
  },
  {
    id: "8",
    boatName: "Aquila",
    image: "/boats/sirocco.png",
    commitment: "egy-verseny",
    event: "Balaton Kupa",
    location: "Fonyód",
    date: "2026. augusztus 14–15.",
    role: "trimmer",
    level: "halado",
  },
  {
    id: "9",
    boatName: "Redline",
    image: "/boats/avalon.png",
    commitment: "szezon",
    event: "Nyári hajózási kör",
    location: "Badacsony",
    date: "2026. június – szeptember",
    role: "kormanyos",
    level: "profi",
  },
  {
    id: "10",
    boatName: "Clover",
    image: "/boats/nemere.png",
    commitment: "egy-verseny",
    event: "Balatonfüredi körverseny",
    location: "Balatonfüred",
    date: "2026. július 30.",
    role: "matroz",
    level: "halado",
  },
  {
    id: "11",
    boatName: "North Star",
    image: "/boats/sirocco.png",
    commitment: "szezon",
    event: "Szezonra felkészült csapat",
    location: "Keszthely",
    date: "2026. május – október",
    role: "trimmer",
    level: "kezdo",
  },
  {
    id: "12",
    boatName: "Breeze Runner",
    image: "/boats/avalon.png",
    commitment: "egy-verseny",
    event: "Hosszútávú regatta",
    location: "Siófok",
    date: "2026. augusztus 22.",
    role: "kormanyos",
    level: "profi",
  },
  {
    id: "13",
    boatName: "Silver Tide",
    image: "/boats/nemere.png",
    commitment: "szezon",
    event: "Tavaszi edzés és bajnokság",
    location: "Balatonkenese",
    date: "2026. április – augusztus",
    role: "matroz",
    level: "halado",
  },
  {
    id: "14",
    boatName: "Spring Wind",
    image: "/boats/sirocco.png",
    commitment: "egy-verseny",
    event: "Esti körverseny",
    location: "Balatonalmádi",
    date: "2026. június 27.",
    role: "trimmer",
    level: "profi",
  },
  {
    id: "15",
    boatName: "Onyx",
    image: "/boats/avalon.png",
    commitment: "szezon",
    event: "Vitorlás szezon kezdete",
    location: "Tapolca",
    date: "2026. május – szeptember",
    role: "matroz",
    level: "kezdo",
  },
  {
    id: "16",
    boatName: "Harbor Queen",
    image: "/boats/nemere.png",
    commitment: "egy-verseny",
    event: "Balaton nyitóverseny",
    location: "Tihany",
    date: "2026. május 16.",
    role: "kormanyos",
    level: "halado",
  },
]
